# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'MyLinuxPool'
steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure_As_Sub-1(321058a0-12a9-46e3-bd92-379511da48d0)'
    appType: 'webAppLinux'
    appName: 'MyWebApp225'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'TOMCAT|9.0-java11'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
